### ISSUE TITLE
Little misspelling

### ISSUE THREAD

**Issue by meliis** [ashryanbeats/node-basic#64]
Cool project, just wanted to point out that the [word](http://dictionary.reference.com/browse/minuscule) is spelled "minuscule" :)

**Comment by Newms34** [comment]
It's a play on the MEAN stack.

**Comment by ashryanbeats** [comment]
Thanks @meliis! 

This is actually a calculated use of the less-used spelling of minuscule, "miniscule":
http://www.merriam-webster.com/dictionary/miniscule
